@extends('layouts.shop.source')
@extends('layouts.shop.footer')
@extends('layouts.shop.about_content')
@extends('layouts.shop.top_header2')
@extends('layouts.shop.header')
@section('title', 'SayatCart | About')