@extends('layouts.shop.source')
@extends('layouts.shop.footer')
@extends('layouts.shop.producttrending')
@extends('layouts.shop.top_header2')
@extends('layouts.shop.header')
@section('title', 'SayatCart | Trending')